In [ ]:
#20BEC0775
#Aanchal Verma
#AI Smartbridge Externship
#Assignment 2

In [ ]:
######################################## TASK 1 #########################################
#Read the dataset and do data pre-processing

In [1]:
#importing the required modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/drug200.csv') # Reading the data
df.head() # Visualizing the data


Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [3]:
df.isnull().sum() # Checking for null values

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [4]:
df['Drug'].unique() # Finding unique category


array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [5]:
df['Drug'].value_counts() # Finding the count of observations based on unique value

DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64

In [6]:
# Splitting the data
x = df.iloc[:,1:5].values
x

array([['F', 'HIGH', 'HIGH', 25.355],
       ['M', 'LOW', 'HIGH', 13.093],
       ['M', 'LOW', 'HIGH', 10.114],
       ['F', 'NORMAL', 'HIGH', 7.798],
       ['F', 'LOW', 'HIGH', 18.043],
       ['F', 'NORMAL', 'HIGH', 8.607],
       ['F', 'NORMAL', 'HIGH', 16.275],
       ['M', 'LOW', 'HIGH', 11.037],
       ['M', 'NORMAL', 'HIGH', 15.171],
       ['M', 'LOW', 'NORMAL', 19.368],
       ['F', 'LOW', 'HIGH', 11.767],
       ['F', 'HIGH', 'NORMAL', 19.199],
       ['M', 'LOW', 'HIGH', 15.376],
       ['F', 'LOW', 'HIGH', 20.942],
       ['F', 'NORMAL', 'HIGH', 12.703],
       ['F', 'HIGH', 'NORMAL', 15.516],
       ['M', 'LOW', 'NORMAL', 11.455],
       ['M', 'HIGH', 'HIGH', 13.972],
       ['M', 'LOW', 'HIGH', 7.298],
       ['F', 'HIGH', 'NORMAL', 25.974],
       ['M', 'LOW', 'NORMAL', 19.128],
       ['M', 'NORMAL', 'HIGH', 25.917],
       ['M', 'LOW', 'NORMAL', 30.568],
       ['F', 'LOW', 'HIGH', 15.036],
       ['F', 'LOW', 'HIGH', 33.486],
       ['F', 'HIGH', 'NORMAL', 18.809],
 

In [7]:
y = pd.get_dummies(df.iloc[:,5:]).values
y


array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1,

In [8]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Activation, Dense
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=21)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((160, 4), (40, 4), (160, 5), (40, 5))

In [ ]:
################################## TASK 2 ################################# 
#Build the ANN model with (input layer, min 3 hidden layers & output layer)

In [9]:
# ANN Model
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
#model.add(Dense(32,activation='relu'))
model.add(Dense(26,activation='relu'))
model.add(Dense(3,activation='softmax'))


model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])


model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 26)                234       
                                                                 
 dense_2 (Dense)             (None, 3)                 81        
                                                                 
Total params: 355
Trainable params: 355
Non-trainable params: 0
_________________________________________________________________


In [ ]:
##########################TASK 3 ######################################
#Test the model with random data

In [11]:
#Splitting the data into train and test
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=21)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape


# Generate random data to test the model
X_new = np.random.rand(5,4)


# Predict the classes of the new data
y_pred = model.predict(X_new)


# Print the predicted classes
print(y_pred)


1/1 [==============================] - 0s 24ms/step
[[0.33279574 0.3509345  0.3162697 ]
 [0.33333334 0.33333334 0.33333334]
 [0.3240552  0.34244266 0.33350217]
 [0.31477958 0.35189167 0.33332875]
 [0.33001417 0.33233422 0.33765164]]
